/**
 * api.js — Centralized Supabase Data Access Layer
 *
 * ALL database interactions go through this module.
 * Feature modules (students.js, sessions.js, etc.) import from api.js only.
 * No other JS file calls supabase directly.
 *
 * Each method returns: { data, error } (Supabase standard shape)
 * Errors are caught and normalized — callers receive consistent responses.
 *
 * Usage:
 *   import { api } from './api.js';
 *   const { data, error } = await api.Students.findByMobile('9876543210');
 */

import { supabaseClient } from './supabase-client.js?v=2.2';

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Normalise any caught exception into the { data, error } contract so every
 * caller can rely on the same shape regardless of what went wrong.
 *
 * @param {unknown} err
 * @returns {{ data: null, error: { message: string, code: string|null, details: unknown } }}
 */
function normalizeError(err) {
  if (err && typeof err === 'object') {
    return {
      data: null,
      error: {
        message: err.message  ?? 'An unexpected error occurred',
        code:    err.code     ?? err.statusCode ?? null,
        details: err.details  ?? err.hint       ?? null,
      },
    };
  }
  return {
    data: null,
    error: { message: String(err), code: null, details: null },
  };
}

/**
 * Wraps a Supabase query promise and normalises the result.
 * Supabase returns { data, error } — we re-use that shape but also catch
 * JS-level throws (network failures, etc.).
 *
 * @param {Promise<{ data: any, error: any }>} queryPromise
 * @returns {Promise<{ data: any, error: any }>}
 */
async function run(queryPromise) {
  try {
    const { data, error, count } = await queryPromise;
    if (error) return normalizeError(error);
    const result = { data, error: null };
    if (count !== undefined && count !== null) {
      result.count = count;
    }
    return result;
  } catch (err) {
    return normalizeError(err);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// api.Students
// ─────────────────────────────────────────────────────────────────────────────

const Students = {
  /**
   * Find an active student by mobile number.
   * Used during attendance marking to identify who is checking in.
   *
   * @param {string} mobile
   * @returns {Promise<{ data: object|null, error: object|null }>}
   */
  async findByMobile(mobile) {
    return run(
      supabaseClient
        .from('students')
        .select('*')
        .eq('mobile_number', mobile)
        .limit(1)
        .maybeSingle()
    );
  },

  /**
   * Find a student by their internal UUID primary key.
   *
   * @param {string} id — UUID
   */
  async findById(id) {
    return run(
      supabaseClient
        .from('students')
        .select('*')
        .eq('id', id)
        .maybeSingle()
    );
  },

  /**
   * Find a student by the business-key student_id (e.g. "STU000042").
   * student_id is generated by a PostgreSQL SEQUENCE in the DB.
   *
   * @param {string} studentId
   */
  async findByStudentId(studentId) {
    return run(
      supabaseClient
        .from('students')
        .select('*')
        .eq('student_id', studentId)
        .maybeSingle()
    );
  },

  /**
   * Find an active student by their University Roll Number.
   *
   * @param {string} rollNumber
   */
  async findByRollNumber(rollNumber) {
    return run(
      supabaseClient
        .from('students')
        .select('*')
        .eq('roll_number', rollNumber)
        .maybeSingle()
    );
  },

  /**
   * Create a new student record using register_student RPC.
   *
   * @param {{ student_name: string, mobile_number: string, lecture_hall: string, roll_number: string }} data
   */
  async create(data) {
    try {
      const { data: res, error } = await supabaseClient.rpc('register_student', {
        p_name: data.student_name,
        p_mobile: data.mobile_number,
        p_hall: data.lecture_hall,
        p_roll: data.roll_number || ''
      });
      if (error) return normalizeError(error);
      if (!res.success) return { data: null, error: { message: res.message } };
      return { data: res.student, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Update mutable fields on an existing student record.
   *
   * @param {string} id — UUID
   * @param {object} data — partial fields to update
   */
  async update(id, data) {
    return run(
      supabaseClient
        .from('students')
        .update(data)
        .eq('id', id)
        .select()
        .single()
    );
  },

  /**
   * Soft-deactivate student account: sets is_active = false.
   *
   * @param {string} id — UUID
   */
  async deactivate(id) {
    return run(
      supabaseClient
        .from('students')
        .update({ is_active: false })
        .eq('id', id)
        .select()
        .single()
    );
  },

  /**
   * Soft-activate student account: sets is_active = true.
   *
   * @param {string} id — UUID
   */
  async activate(id) {
    return run(
      supabaseClient
        .from('students')
        .update({ is_active: true })
        .eq('id', id)
        .select()
        .single()
    );
  },

  /**
   * Check whether a mobile number is already in use.
   * Pass excludeId to allow the current student's own number through during updates.
   *
   * @param {string} mobile
   * @param {string|null} excludeId — UUID of the student to skip
   * @returns {Promise<{ data: boolean, error: object|null }>} data=true means duplicate exists
   */
  async checkMobileDuplicate(mobile, excludeId = null) {
    try {
      let query = supabaseClient
        .from('students')
        .select('id', { count: 'exact', head: true })
        .eq('mobile_number', mobile);

      if (excludeId) {
        query = query.neq('id', excludeId);
      }

      const { count, error } = await query;
      if (error) return normalizeError(error);
      return { data: count > 0, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Paginated, filterable student list.
   *
   * @param {{ hall?: string, search?: string, isActive?: boolean, page?: number, limit?: number }} options
   * @returns {Promise<{ data: object[], error: object|null }>}
   */
  async list({ hall, search, isActive, page = 1, limit = 50 } = {}) {
    try {
      let query = supabaseClient
        .from('students')
        .select('*')
        .order('student_name', { ascending: true });

      if (hall     !== undefined && hall     !== null) query = query.eq('lecture_hall', hall);
      if (isActive !== undefined && isActive !== null) query = query.eq('is_active', isActive);
      if (search) {
        query = query.or(
          `student_name.ilike.%${search}%,student_id.ilike.%${search}%,mobile_number.ilike.%${search}%,roll_number.ilike.%${search}%`
        );
      }

      const from = (page - 1) * limit;
      const to   = from + limit - 1;
      query = query.range(from, to);

      const { data, error } = await query;
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Count students, optionally filtered by hall and/or active status.
   *
   * @param {{ hall?: string, isActive?: boolean }} options
   * @returns {Promise<{ data: number, error: object|null }>}
   */
  async count({ hall, isActive } = {}) {
    try {
      let query = supabaseClient
        .from('students')
        .select('*', { count: 'exact', head: true });

      if (hall     !== undefined && hall     !== null) query = query.eq('lecture_hall', hall);
      if (isActive !== undefined && isActive !== null) query = query.eq('is_active', isActive);

      const { count, error } = await query;
      if (error) return normalizeError(error);
      return { data: count, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Count students whose overall attendance percentage is below the given threshold.
   * Joins student_attendance_summary to get the percentage.
   *
   * @param {number} threshold — e.g. 75
   * @returns {Promise<{ data: number, error: object|null }>}
   */
  async countBelowThreshold(threshold) {
    try {
      const { count, error } = await supabaseClient
        .from('attendance_summary')
        .select('*', { count: 'exact', head: true })
        .lt('attendance_percentage', threshold);

      if (error) return normalizeError(error);
      return { data: count, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Delete a student profile permanently (cascades to summary & records).
   *
   * @param {string} id — Student UUID
   */
  async delete(id) {
    return run(
      supabaseClient
        .from('students')
        .delete()
        .eq('id', id)
        .select()
        .single()
    );
  },

  /**
   * Get all student IDs and mobile numbers to validate bulk imports efficiently.
   */
  async getAllStudentIdsAndMobiles() {
    return run(
      supabaseClient
        .from('students')
        .select('roll_number, mobile_number')
    );
  },

  /**
   * Delete multiple students in a single query.
   *
   * @param {Array<string>} idsArray
   */
  async deleteMultiple(idsArray) {
    return run(
      supabaseClient
        .from('students')
        .delete()
        .in('id', idsArray)
    );
  },

  /**
   * Reset all student profiles in the database.
   */
  async resetAll() {
    try {
      const { data: res, error } = await supabaseClient.rpc('reset_all_students');
      if (error) return normalizeError(error);
      return { data: true, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// api.Faculty
// ─────────────────────────────────────────────────────────────────────────────

const Faculty = {
  /**
   * Look up a faculty member using their Supabase auth UUID.
   * Used after sign-in to hydrate the user object.
   *
   * @param {string} authId — UUID from auth.users
   */
  async findByAuthId(authId) {
    return run(
      supabaseClient
        .from('faculty')
        .select('*')
        .eq('auth_id', authId)
        .maybeSingle()
    );
  },

  /**
   * @param {string} id — UUID
   */
  async findById(id) {
    return run(
      supabaseClient
        .from('faculty')
        .select('*')
        .eq('id', id)
        .maybeSingle()
    );
  },

  /**
   * @param {string} facultyId — custom faculty ID string (e.g., 'FAC001')
   */
  async findByFacultyId(facultyId) {
    return run(
      supabaseClient
        .from('faculty')
        .select('*')
        .eq('faculty_id', facultyId)
        .maybeSingle()
    );
  },

  /**
   * @param {string} email — email address
   */
  async findByEmail(email) {
    return run(
      supabaseClient
        .from('faculty')
        .select('*')
        .eq('email', email)
        .maybeSingle()
    );
  },

  /**
   * Paginated faculty list, optionally filtered by status.
   *
   * @param {{ page?: number, limit?: number, isActive?: boolean }} options
   */
  async list({ page = 1, limit = 50, isActive = undefined } = {}) {
    const from = (page - 1) * limit;
    const to   = from + limit - 1;
    let query = supabaseClient
      .from('faculty')
      .select('*', { count: 'exact' })
      .neq('faculty_id', 'SYSTEM_ARCHIVE')
      .order('faculty_name', { ascending: true })
      .range(from, to);

    if (isActive !== undefined) {
      query = query.eq('is_active', isActive);
    }

    return run(query);
  },

  /**
   * Insert a new faculty record.
   *
   * @param {object} data
   */
  async create(data) {
    return run(
      supabaseClient
        .from('faculty')
        .insert(data)
        .select()
        .single()
    );
  },

  /**
   * Update a faculty record, including possible lecture_hall reassignment.
   *
   * @param {string} id — UUID
   * @param {object} data — partial fields
   */
  async update(id, data) {
    return run(
      supabaseClient
        .from('faculty')
        .update(data)
        .eq('id', id)
        .select()
        .single()
    );
  },

  /**
   * Soft-deactivate faculty account.
   *
   * @param {string} id — UUID
   */
  async deactivate(id) {
    return run(
      supabaseClient
        .from('faculty')
        .update({ is_active: false })
        .eq('id', id)
        .select()
        .single()
    );
  },

  /**
   * Soft-activate faculty account.
   *
   * @param {string} id — UUID
   */
  async activate(id) {
    return run(
      supabaseClient
        .from('faculty')
        .update({ is_active: true })
        .eq('id', id)
        .select()
        .single()
    );
  },

  /**
   * Create a faculty auth user AND faculty profile in a single atomic RPC call.
   *
   * Uses the SECURITY DEFINER function create_faculty_account() which:
   *   1. Inserts directly into auth.users (bypasses email confirmation)
   *   2. Inserts into public.faculty in the same transaction
   *   3. Returns success/failure JSON
   *
   * This avoids the FK violation (23503) caused by inserting into faculty
   * before the auth user is confirmed.
   *
   * @param {{ name: string, facultyId: string, email: string, password: string }} data
   * @returns {Promise<{ data: object|null, error: object|null }>}
   */
  async createFacultyAccount({ name, facultyId, email, password }) {
    try {
      const { data: res, error } = await supabaseClient.rpc('create_faculty_account', {
        p_name:       name,
        p_faculty_id: facultyId,
        p_email:      email,
        p_password:   password,
      });
      if (error) return normalizeError(error);
      if (!res.success) return { data: null, error: { message: res.message } };
      return { data: res.faculty, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Delete a faculty profile permanently.
   *
   * @param {string} id — Faculty UUID
   */
  async delete(id) {
    return run(
      supabaseClient
        .from('faculty')
        .delete()
        .eq('id', id)
        .select()
        .single()
    );
  },

  /**
   * Permanently delete a faculty account, reassigning historical sessions
   * and clean up the auth user account.
   *
   * @param {string} id — Faculty UUID
   */
  async deletePermanently(id) {
    try {
      const { data: res, error } = await supabaseClient.rpc('delete_faculty_permanently', {
        p_faculty_id: id
      });
      if (error) return normalizeError(error);
      if (!res.success) return { data: null, error: { message: res.message } };
      return { data: true, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Verify if a faculty member has any dependent attendance sessions or audit logs.
   *
   * @param {string} id — Faculty profile UUID
   * @param {string} authId — Faculty auth.users UUID
   * @returns {Promise<{ data: { hasDependencies: boolean }, error: object|null }>}
   */
  async checkDependencies(id, authId) {
    try {
      const { count: sessionCount, error: sessionErr } = await supabaseClient
        .from('attendance_sessions')
        .select('*', { count: 'exact', head: true })
        .eq('faculty_id', id);

      if (sessionErr) return normalizeError(sessionErr);

      let auditCount = 0;
      if (authId) {
        const { count: actorAuditCount, error: auditErr } = await supabaseClient
          .from('audit_logs')
          .select('*', { count: 'exact', head: true })
          .or(`actor_id.eq.${authId},target_id.eq.${id}`);
        if (auditErr) return normalizeError(auditErr);
        auditCount = actorAuditCount || 0;
      }

      return { data: { hasDependencies: (sessionCount > 0 || auditCount > 0) }, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Delete multiple faculty members permanently in a single transaction.
   *
   * @param {Array<string>} idsArray
   */
  async deleteMultiplePermanently(idsArray) {
    try {
      const { data: res, error } = await supabaseClient.rpc('delete_multiple_faculty', {
        p_faculty_ids: idsArray
      });
      if (error) return normalizeError(error);
      if (!res.success) return { data: null, error: { message: res.message } };
      return { data: true, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Reset all faculty accounts in the database (except SYSTEM_ARCHIVE).
   */
  async resetAll() {
    try {
      const { data: res, error } = await supabaseClient.rpc('reset_all_faculty');
      if (error) return normalizeError(error);
      if (!res.success) return { data: null, error: { message: res.message } };
      return { data: true, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// api.Admins
// ─────────────────────────────────────────────────────────────────────────────

const Admins = {
  /**
   * Find an admin record by Supabase auth UUID.
   *
   * @param {string} authId
   */
  async findByAuthId(authId) {
    return run(
      supabaseClient
        .from('admins')
        .select('*')
        .eq('auth_id', authId)
        .maybeSingle()
    );
  },

  /**
   * Find an admin record by username.
   *
   * @param {string} username
   */
  async findByUsername(username) {
    return run(
      supabaseClient
        .from('admins')
        .select('*')
        .eq('username', username)
        .maybeSingle()
    );
  },

  /**
   * @param {string} email — email address
   */
  async findByEmail(email) {
    return run(
      supabaseClient
        .from('admins')
        .select('*')
        .eq('email', email)
        .maybeSingle()
    );
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// api.Sessions
// ─────────────────────────────────────────────────────────────────────────────

// Forward-declare RPC so Sessions.close() can call it before RPC is declared.
// The real binding happens via the final `api` object — we use a thunk to avoid
// a circular reference at definition time.
let _rpcRef = null;

const Sessions = {
  /**
   * Open a new attendance session using create_attendance_session RPC.
   *
   * @param {{ lecture_hall: string, session_label: string, faculty_id: string, window_seconds: number }} data
   */
  async create(data) {
    try {
      const { data: res, error } = await supabaseClient.rpc('create_attendance_session', {
        p_hall: data.lecture_hall,
        p_session: data.session_label,
        p_faculty_uuid: data.faculty_id,
        p_window_seconds: parseInt(data.window_seconds || '300', 10)
      });
      if (error) return normalizeError(error);
      if (!res.success) return { data: null, error: { message: res.message } };
      return { data: { id: res.session_id, attendance_code: res.attendance_code, end_time: res.end_time }, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * @param {string} id — UUID
   */
  async findById(id) {
    return run(
      supabaseClient
        .from('attendance_sessions')
        .select('*, faculty(faculty_name)')
        .eq('id', id)
        .maybeSingle()
    );
  },

  /**
   * Find the most recent ACTIVE session for a given lecture hall.
   * Returns null (not an error) if no active session exists.
   *
   * @param {string} hall — e.g. 'LH-01'
   */
  async findActive(hall) {
    return run(
      supabaseClient
        .from('attendance_sessions')
        .select('*, faculty(faculty_name)')
        .eq('lecture_hall', hall)
        .eq('status', 'active')
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle()
    );
  },

  /**
   * Find any active session for a specific faculty member.
   * Used for session recovery.
   *
   * @param {string} facultyId — UUID
   */
  async findActiveForFaculty(facultyId) {
    return run(
      supabaseClient
        .from('attendance_sessions')
        .select('*')
        .eq('faculty_id', facultyId)
        .eq('status', 'active')
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle()
    );
  },

  /**
   * Return ALL currently active sessions across all halls, with faculty details.
   * Used by the admin dashboard to show a live overview.
   */
  async findAllActive() {
    return run(
      supabaseClient
        .from('attendance_sessions')
        .select('*, faculty(faculty_name)')
        .eq('status', 'active')
        .order('created_at', { ascending: false })
    );
  },

  /**
   * Rotate the 4-digit attendance code for a running session using refresh_attendance_code RPC.
   *
   * @param {string} id — session UUID
   */
  async updateCode(id) {
    try {
      const { data: res, error } = await supabaseClient.rpc('refresh_attendance_code', {
        p_session_id: id
      });
      if (error) return normalizeError(error);
      if (!res.success) return { data: null, error: { message: res.message } };
      return { data: { id, attendance_code: res.attendance_code }, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Close a session and mark all non-attending students as absent.
   *
   * @param {string} id — session UUID
   */
  async close(id) {
    return _rpcRef.closeSession(id);
  },

  /**
   * List all sessions for a calendar date, optionally scoped to a hall.
   *
   * @param {string}      date — ISO date 'YYYY-MM-DD'
   * @param {string|null} hall
   */
  async listByDate(date, hall = null) {
    try {
      let query = supabaseClient
        .from('attendance_sessions')
        .select('*, faculty(faculty_name)')
        .gte('created_at', `${date}T00:00:00.000Z`)
        .lte('created_at', `${date}T23:59:59.999Z`)
        .order('created_at', { ascending: true });

      if (hall) query = query.eq('lecture_hall', hall);

      const { data, error } = await query;
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * List sessions within a date range, optionally scoped to a hall.
   *
   * @param {string}      from — ISO date 'YYYY-MM-DD'
   * @param {string}      to   — ISO date 'YYYY-MM-DD'
   * @param {string|null} hall
   */
  async listByDateRange(from, to, hall = null) {
    try {
      let query = supabaseClient
        .from('attendance_sessions')
        .select('*, faculty(faculty_name)')
        .gte('created_at', `${from}T00:00:00.000Z`)
        .lte('created_at', `${to}T23:59:59.999Z`)
        .order('created_at', { ascending: true });

      if (hall) query = query.eq('lecture_hall', hall);

      const { data, error } = await query;
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Aggregate present / absent / total counts for a closed session.
   *
   * @param {string} sessionId — UUID
   * @returns {Promise<{ data: { present: number, absent: number, total: number }, error: object|null }>}
   */
  async getSessionSummary(sessionId) {
    try {
      const { data, error } = await supabaseClient
        .from('attendance_records')
        .select('status')
        .eq('session_id', sessionId);

      if (error) return normalizeError(error);

      const present = data.filter(r => r.status === 'present').length;
      const absent  = data.filter(r => r.status === 'absent').length;

      return { data: { present, absent, total: present + absent }, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// api.Records
// ─────────────────────────────────────────────────────────────────────────────

const Records = {
  /**
   * Insert a single attendance record.
   *
   * @param {{ student_id: string, session_id: string, status: 'present'|'absent', marked_at?: string }} data
   */
  async insert(data) {
    return run(
      supabaseClient
        .from('attendance_records')
        .insert(data)
        .select()
        .single()
    );
  },

  /**
   * Check whether a record already exists for a student in a session.
   * Used to enforce the UNIQUE (student_id, session_id) constraint client-side.
   *
   * @param {string} studentId  — UUID
   * @param {string} sessionId  — UUID
   * @returns {Promise<{ data: boolean, error: object|null }>} data=true means duplicate
   */
  async findDuplicate(studentId, sessionId) {
    try {
      const { count, error } = await supabaseClient
        .from('attendance_records')
        .select('*', { count: 'exact', head: true })
        .eq('student_id', studentId)
        .eq('session_id', sessionId);

      if (error) return normalizeError(error);
      return { data: count > 0, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * All attendance records for a session, joined with student details.
   *
   * @param {string} sessionId — UUID
   */
  async bySession(sessionId) {
    return run(
      supabaseClient
        .from('attendance_records')
        .select('*, students(student_id, student_name, roll_number, mobile_number, lecture_hall)')
        .eq('session_id', sessionId)
        .order('marked_at', { ascending: true })
    );
  },

  /**
   * Attendance history for a single student within a date range.
   *
   * @param {string} studentId — UUID
   * @param {string} from      — ISO date 'YYYY-MM-DD'
   * @param {string} to        — ISO date 'YYYY-MM-DD'
   */
  async byStudent(studentId, from, to) {
    return run(
      supabaseClient
        .from('attendance_records')
        .select('*, attendance_sessions(session_label, lecture_hall, created_at, status)')
        .eq('student_id', studentId)
        .gte('marked_at', `${from}T00:00:00.000Z`)
        .lte('marked_at', `${to}T23:59:59.999Z`)
        .order('marked_at', { ascending: false })
    );
  },

  /**
   * All attendance records for a lecture hall within a date range.
   * Used for LH-level reporting.
   *
   * @param {string} hall — e.g. 'LH-01'
   * @param {string} from — ISO date
   * @param {string} to   — ISO date
   */
  async byHall(hall, from, to) {
    return run(
      supabaseClient
        .from('attendance_records')
        .select('*, students(student_id, student_name, roll_number), attendance_sessions(session_label, lecture_hall, created_at)')
        .eq('lecture_hall', hall)
        .gte('marked_at', `${from}T00:00:00.000Z`)
        .lte('marked_at', `${to}T23:59:59.999Z`)
        .order('marked_at', { ascending: false })
    );
  },

  /**
   * All records for a given calendar date, optionally filtered by hall.
   *
   * @param {string}      date — 'YYYY-MM-DD'
   * @param {string|null} hall
   */
  async byDate(date, hall = null) {
    try {
      let query = supabaseClient
        .from('attendance_records')
        .select('*, students(student_id, student_name, roll_number, lecture_hall), attendance_sessions(session_label, lecture_hall, created_at)')
        .gte('marked_at', `${date}T00:00:00.000Z`)
        .lte('marked_at', `${date}T23:59:59.999Z`)
        .order('marked_at', { ascending: true });

      if (hall) query = query.eq('lecture_hall', hall);

      const { data, error } = await query;
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Absent records for a given date, optionally filtered by hall and session label.
   *
   * @param {string}      date         — 'YYYY-MM-DD'
   * @param {string|null} hall
   * @param {string|null} sessionLabel — e.g. 'S1'
   */
  async absentees(date, hall = null, sessionLabel = null) {
    try {
      let query = supabaseClient
        .from('attendance_records')
        .select('*, students(student_id, student_name, roll_number, mobile_number, lecture_hall), attendance_sessions(session_label, lecture_hall, created_at)')
        .eq('status', 'absent')
        .gte('marked_at', `${date}T00:00:00.000Z`)
        .lte('marked_at', `${date}T23:59:59.999Z`)
        .order('marked_at', { ascending: true });

      if (hall)         query = query.eq('lecture_hall', hall);
      if (sessionLabel) query = query.eq('session_label', sessionLabel);

      const { data, error } = await query;
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Fetch all records, optionally within range (used primarily for backup downloads).
   */
  async listAll() {
    return run(
      supabaseClient
        .from('attendance_records')
        .select('*')
        .order('marked_at', { ascending: false })
    );
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// api.Summary
// ─────────────────────────────────────────────────────────────────────────────

const Summary = {
  /**
   * Get the attendance summary row for a student.
   *
   * @param {string} studentId — UUID
   */
  async findByStudent(studentId) {
    return run(
      supabaseClient
        .from('attendance_summary')
        .select('*')
        .eq('student_id', studentId)
        .maybeSingle()
    );
  },

  /**
   * Ensure a summary row exists for a student.
   * Inserts with 0/0/0 if not present; a no-op if it already exists.
   *
   * @param {string} studentId — UUID
   */
  async ensure(studentId) {
    return run(
      supabaseClient
        .from('attendance_summary')
        .upsert(
          {
            student_id:            studentId,
            present_count:         0,
            absent_count:          0,
          },
          { onConflict: 'student_id', ignoreDuplicates: true }
        )
        .select()
        .single()
    );
  },

  /**
   * Return summary rows joined with student details for an entire lecture hall.
   *
   * @param {string} hall — e.g. 'LH-03'
   */
  async byHall(hall) {
    return run(
      supabaseClient
        .from('attendance_summary')
        .select('*, students!inner(student_id, student_name, roll_number, mobile_number, lecture_hall, is_active)')
        .eq('students.lecture_hall', hall)
        .eq('students.is_active', true)
        .order('students.student_name', { ascending: true })
    );
  },

  /**
   * Paginated summary with optional hall and percentage-range filters.
   *
   * @param {{ hall?: string, minPct?: number, maxPct?: number, page?: number, limit?: number }} options
   */
  async all({ hall, minPct, maxPct, page = 1, limit = 50 } = {}) {
    try {
      let query = supabaseClient
        .from('attendance_summary')
        .select('*, students!inner(student_id, student_name, roll_number, lecture_hall, is_active)')
        .eq('students.is_active', true)
        .order('attendance_percentage', { ascending: true });

      if (hall   !== undefined && hall   !== null) query = query.eq('students.lecture_hall', hall);
      if (minPct !== undefined && minPct !== null) query = query.gte('attendance_percentage', minPct);
      if (maxPct !== undefined && maxPct !== null) query = query.lte('attendance_percentage', maxPct);

      const from = (page - 1) * limit;
      const to   = from + limit - 1;
      query = query.range(from, to);

      const { data, error } = await query;
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Students below the low-attendance threshold, optionally scoped to a hall.
   *
   * @param {number}      threshold — percentage, e.g. 75
   * @param {string|null} hall
   */
  async belowThreshold(threshold, hall = null) {
    try {
      let query = supabaseClient
        .from('attendance_summary')
        .select('*, students!inner(student_id, student_name, roll_number, mobile_number, lecture_hall, is_active)')
        .lt('attendance_percentage', threshold)
        .eq('students.is_active', true)
        .order('attendance_percentage', { ascending: true });

      if (hall) query = query.eq('students.lecture_hall', hall);

      const { data, error } = await query;
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// api.Settings
// ─────────────────────────────────────────────────────────────────────────────

const Settings = {
  /**
   * Fetch all key-value settings rows.
   */
  async getAll() {
    return run(
      supabaseClient
        .from('settings')
        .select('*')
        .order('key', { ascending: true })
    );
  },

  /**
   * Fetch the value for a single setting key.
   *
   * @param {string} key
   * @returns {Promise<{ data: string|null, error: object|null }>}
   */
  async get(key) {
    try {
      const { data, error } = await supabaseClient
        .from('settings')
        .select('value')
        .eq('key', key)
        .maybeSingle();

      if (error) return normalizeError(error);
      return { data: data?.value ?? null, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Upsert a setting value and record who changed it.
   *
   * @param {string} key
   * @param {string} value
   * @param {string} updatedById — faculty/admin UUID who made the change
   */
  async upsert(key, value, updatedById) {
    return run(
      supabaseClient
        .from('settings')
        .upsert(
          { key, value, updated_by: updatedById, updated_at: new Date().toISOString() },
          { onConflict: 'key' }
        )
        .select()
        .single()
    );
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// api.Audit
// ─────────────────────────────────────────────────────────────────────────────

const Audit = {
  /**
   * Insert a single audit log entry.
   *
   * @param {{ action: string, actor_id?: string, actor_role?: string, target_table?: string, target_id?: string, details?: object }} data
   */
  async insert(data) {
    return run(
      supabaseClient
        .from('audit_logs')
        .insert({
          ...data,
          created_at: data.created_at ?? new Date().toISOString(),
        })
        .select()
        .single()
    );
  },

  /**
   * Paginated, filterable audit log list.
   *
   * @param {{ action?: string, actorRole?: string, from?: string, to?: string, page?: number, limit?: number }} options
   */
  async list({ action, actorRole, from, to, page = 1, limit = 100 } = {}) {
    try {
      let query = supabaseClient
        .from('audit_logs')
        .select('*')
        .order('created_at', { ascending: false });

      if (action)    query = query.eq('action', action);
      if (actorRole) query = query.eq('actor_role', actorRole);
      if (from)      query = query.gte('created_at', `${from}T00:00:00.000Z`);
      if (to)        query = query.lte('created_at', `${to}T23:59:59.999Z`);

      const offset  = (page - 1) * limit;
      const ceiling = offset + limit - 1;
      query = query.range(offset, ceiling);

      const { data, error } = await query;
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// api.Auth
// ─────────────────────────────────────────────────────────────────────────────

const Auth = {
  /**
   * Sign in with email + password via Supabase Auth.
   *
   * @param {string} email
   * @param {string} password
   * @returns {Promise<{ data: { session, user }, error: object|null }>}
   */
  async signIn(email, password) {
    try {
      const { data, error } = await supabaseClient.auth.signInWithPassword({ email, password });
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Sign out the currently authenticated user.
   */
  async signOut() {
    try {
      const { error } = await supabaseClient.auth.signOut();
      if (error) return normalizeError(error);
      return { data: true, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Get the current active session (null if not signed in).
   *
   * @returns {Promise<{ data: Session|null, error: object|null }>}
   */
  async getSession() {
    try {
      const { data, error } = await supabaseClient.auth.getSession();
      if (error) return normalizeError(error);
      return { data: data?.session ?? null, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Get the currently authenticated user object.
   *
   * @returns {Promise<{ data: User|null, error: object|null }>}
   */
  async getUser() {
    try {
      const { data, error } = await supabaseClient.auth.getUser();
      if (error) return normalizeError(error);
      return { data: data?.user ?? null, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Subscribe to auth state changes (sign-in, sign-out, token refresh).
   *
   * @param {(event: string, session: Session|null) => void} callback
   * @returns {{ data: { subscription: Subscription } }} — call subscription.unsubscribe() to clean up
   */
  onAuthStateChange(callback) {
    return supabaseClient.auth.onAuthStateChange(callback);
  },

  /**
   * Reset a faculty password via the reset_faculty_password SECURITY DEFINER function.
   *
   * @param {string} email
   * @param {string} newPassword
   */
  async resetFacultyPassword(email, newPassword) {
    try {
      const { data: res, error } = await supabaseClient.rpc('reset_faculty_password', {
        p_email: email,
        p_new_password: newPassword
      });
      if (error) return normalizeError(error);
      if (!res.success) return { data: null, error: { message: res.message } };
      return { data: true, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// api.RPC
// ─────────────────────────────────────────────────────────────────────────────

const RPC = {
  /**
   * Mark attendance via the mark_attendance PostgreSQL function.
   * The DB function handles: code validation, duplicate prevention, summary update, device binding.
   *
   * @param {string} rollNumber — student's University Roll Number
   * @param {string} code       — 4-digit attendance code shown in the classroom
   * @param {string} deviceHash — 32-character SHA-256 browser hardware fingerprint
   * @returns {Promise<{ data: { success: boolean, message: string, student_name?: string }, error: object|null }>}
   */
  async markAttendance(rollNumber, code, deviceHash) {
    try {
      const { data, error } = await supabaseClient.rpc('mark_attendance', {
        p_roll_number: rollNumber,
        p_code:        code,
        p_device_hash: deviceHash,
      });
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Override a student's attendance from Absent to Present manually (Faculty/Admin only).
   *
   * @param {string} sessionId
   * @param {string} studentId — UUID
   * @param {string} status - 'P' or 'A'
   * @param {string} reason
   */
  async overrideStudentAttendance(sessionId, studentId, status, reason) {
    try {
      const { data, error } = await supabaseClient.rpc('override_student_attendance', {
        p_session_id: sessionId,
        p_student_id: studentId,
        p_status:     status,
        p_reason:     reason,
      });
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Reset a student's bound device ID (Admin only).
   *
   * @param {string} studentId — UUID
   */
  async resetStudentDevice(studentId) {
    try {
      const { data, error } = await supabaseClient.rpc('reset_student_device', {
        p_student_id: studentId,
      });
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Close a session and auto-mark remaining students absent.
   *
   * @param {string} sessionId — UUID of the session to close
   * @returns {Promise<{ data: any, error: object|null }>}
   */
  async closeSession(sessionId) {
    try {
      const { data, error } = await supabaseClient.rpc('close_session_and_mark_absent', {
        session_uuid: sessionId,
      });
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Fetch aggregated statistics for the admin dashboard via RPC.
   *
   * @returns {Promise<{ data: object|null, error: object|null }>}
   */
  async getAdminDashboardStats() {
    try {
      const { data, error } = await supabaseClient.rpc('get_admin_dashboard_stats');
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Fetch aggregated statistics for the admin Students page via RPC.
   */
  async getAdminStudentsStats() {
    try {
      const { data, error } = await supabaseClient.rpc('get_admin_students_stats');
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Fetch aggregated statistics for the admin Faculty page via RPC.
   */
  async getAdminFacultyStats() {
    try {
      const { data, error } = await supabaseClient.rpc('get_admin_faculty_stats');
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Fetch aggregated statistics for the admin Attendance page via RPC.
   */
  async getAdminAttendanceStats() {
    try {
      const { data, error } = await supabaseClient.rpc('get_admin_attendance_stats');
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Fetch aggregated statistics for the admin Reports page via RPC.
   */
  async getAdminReportsStats() {
    try {
      const { data, error } = await supabaseClient.rpc('get_admin_reports_stats');
      if (error) return normalizeError(error);
      return { data, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },

  /**
   * Bulk import students and seed summaries in a single transaction.
   *
   * @param {Array} studentsArray
   */
  async bulkImportStudents(studentsArray) {
    try {
      const { data: res, error } = await supabaseClient.rpc('bulk_import_students', {
        p_students: studentsArray
      });
      if (error) return normalizeError(error);
      return { data: res, error: null };
    } catch (err) {
      return normalizeError(err);
    }
  },
};


// Wire up the deferred RPC reference for Sessions.close()
_rpcRef = RPC;

// ─────────────────────────────────────────────────────────────────────────────
// Assemble & export
// ─────────────────────────────────────────────────────────────────────────────

export const api = Object.freeze({
  Students,
  Faculty,
  Admins,
  Sessions,
  Records,
  Summary,
  Settings,
  Audit,
  Auth,
  RPC,
});

// Named namespace exports for tree-shaking-friendly imports:
//   import { Students, Sessions } from './api.js';
export { Students, Faculty, Admins, Sessions, Records, Summary, Settings, Audit, Auth, RPC };

export default api;
