/**
 * SmartAttend — College Smart Attendance System
 * Application Configuration
 *
 * ═══════════════════════════════════════════════════════════════════
 *  SETUP INSTRUCTIONS
 * ═══════════════════════════════════════════════════════════════════
 *  1. Go to https://supabase.com and create a new project
 *  2. Navigate to: Project Settings → API
 *  3. Copy your Project URL and anon/public key
 *  4. Replace the placeholder values in the SUPABASE CONNECTION section
 *  5. This is the ONLY file you need to edit for the database connection
 *
 *  ⚠ SECURITY RULES:
 *  - NEVER add SUPABASE_SERVICE_ROLE_KEY here (browser-unsafe)
 *  - NEVER commit this file with real keys to a public repository
 *  - Only SUPABASE_URL and SUPABASE_ANON_KEY belong in this file
 * ═══════════════════════════════════════════════════════════════════
 */

const APP_CONFIG = {

  // ── Supabase Connection ─────────────────────────────────────────────────
  // Replace these two values after creating your Supabase project.
  // All other files read credentials from here — no other file needs to change.
  SUPABASE_URL:      'https://gvgaafrfwclmppuqqvac.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Z2FhZnJmd2NsbXBwdXFxdmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzODg0MTksImV4cCI6MjA5NDk2NDQxOX0.aXdZDpv_D9ZiEzEK2wCkP6fEbnLLSBbPsg0VbZEM1uk',

  // ── Lecture Halls (Fixed — do not change) ──────────────────────────────
  LECTURE_HALLS: ['LH-01', 'LH-02', 'LH-03', 'LH-04', 'LH-05', 'LH-06'],

  // ── Session Labels (Fixed — do not change) ─────────────────────────────
  SESSION_LABELS: ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7'],

  // ── Student ID Format (Fixed) ──────────────────────────────────────────
  // Generated by PostgreSQL SEQUENCE — format: STU000001, STU000002, ...
  // These constants are for display and formatting only; DB generates the actual ID.
  STUDENT_ID_PREFIX:  'STU',
  STUDENT_ID_PADDING: 6,

  // ── Attendance Code (Fixed) ────────────────────────────────────────────
  // 4-digit numeric code: '0000' to '9999'
  CODE_LENGTH: 4,

  // ── Default Settings ───────────────────────────────────────────────────
  // These values are SEEDED into the settings table on first DB setup.
  // After that, they are managed from the Admin Settings page — not here.
  DEFAULT_COLLEGE_NAME:        'College Smart Attendance System',
  DEFAULT_ACADEMIC_YEAR:       '2026–2027',
  DEFAULT_WINDOW_MINUTES:      5,     // Attendance session duration in minutes
  DEFAULT_LOW_ATT_THRESHOLD:   75,    // Low attendance alert threshold (%)
  DEFAULT_EXPORT_FORMAT:       'xlsx', // 'xlsx' | 'csv' | 'pdf'

  // ── Application Metadata ───────────────────────────────────────────────
  APP_NAME:    'SmartAttend',
  APP_VERSION: '1.0.0',

};

// Freeze the config to prevent accidental mutation at runtime
Object.freeze(APP_CONFIG);
